# Generated by Django 4.1.2 on 2022-11-02 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import ecomm.apps.fnd.models.fnd


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fnd',
            fields=[
                ('is_blocked', models.BooleanField(default=False)),
                ('is_shown', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.JSONField(blank=True, max_length=80, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecomm.apps.fnd.models.fnd.fnd_logo_upload_to)),
                ('main_layout', models.CharField(choices=[('layouts/upper.html', 'Upper'), ('layouts/lower.html', 'Lower'), ('layouts/left.html', 'Left'), ('layouts/right.html', 'Right')], default='layouts/upper.html', max_length=20)),
                ('content_layout', models.CharField(choices=[('list_container-row', 'Row'), ('list_container-col', 'Column')], default='list_container-row', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=6)),
                ('langs', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foundation',
                'verbose_name_plural': 'Foundations',
            },
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FndTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('fnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='fnd.fnd')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
