# Generated by Django 4.1.2 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ext_name',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
