# Generated by Django 4.1.2 on 2022-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='title',
        ),
        migrations.AlterField(
            model_name='productbase',
            name='name',
            field=models.JSONField(),
        ),
    ]
