# Generated by Django 4.1.2 on 2022-11-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0002_remove_producttype_title_alter_productbase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saletype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saletype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='saletype',
            name='updated_at',
        ),
    ]
