# Generated by Django 4.1.2 on 2022-11-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0003_fnd_id_alter_fnd_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnd',
            name='id',
        ),
        migrations.AlterField(
            model_name='fnd',
            name='alias',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
