# Generated by Django 4.1.2 on 2022-11-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0003_remove_coupon_created_at_remove_coupon_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='trs',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='trs',
        ),
    ]
