# Generated by Django 4.1.2 on 2022-11-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0004_remove_fnd_id_alter_fnd_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
