# Generated by Django 4.1.2 on 2022-11-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0004_rename_trs_productattribute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name',
            field=models.JSONField(default={'en': 'qqqq'}),
            preserve_default=False,
        ),
    ]
