# Generated by Django 4.1.2 on 2022-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnd', '0006_alter_product_ext_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='in_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext_name',
            field=models.JSONField(default=dict),
        ),
    ]
